version: '2'
services:
    web:
        build: .
        ports:
            - "3001:3001"
        env_file:
            - .env
        environment:
            - MONGO_URI=mongodb://mongo:27017/tapowar
            - PORT=3001
            - NODE_ENV=development
        volumes:
            - .:/usr/src/app
        command: "bin/local"
        depends_on:
            - mongo
    mongo:
        image: mongo
        ports:
            - '27017:27017'
        volumes:
            - tap_o_war:/data/db
volumes:
    tap_o_war: